### ISSUE TITLE
import openmc.lib fails

### ISSUE THREAD

**Issue by gridley** [exasmr/openmc#26]
Built without OpenMP, pure single thread CPU execution.

```
>>> import openmc.lib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gavin/Code/openmc/openmc/lib/__init__.py", line 54, in <module>
    from .filter import *
  File "/home/gavin/Code/openmc/openmc/lib/filter.py", line 38, in <module>
    _dll.openmc_energyfunc_filter_set_data.restype = c_int
  File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/gavin/Code/openmc/openmc/lib/libopenmc.so: undefined symbol: openmc_energyfunc_filter_set_data.
Did you mean: 'openmc_energy_filter_set_bins'?
```

It's almost as if `__cplusplus` isn't defined in capi.h. Hm. Currently investigating.

**Comment by gridley** [comment]
OK, it's because some C API functions are commented out during the OpenMP conversion.
